Repository chihab-inc/myPortal, pull requests merged in 2023-10, with the labels that each got.

#109 PR - fix/toast
  public/controllers/database/themeDB.js
Labels: bug

#111 PR - fix/button-group-padding
  public/components/ButtonGroup.js
  public/style.css
Labels: bug

#114 PR - f/build
  build.yml
Labels: feature

#116 build.yml
  .github/workflows/node.js.yml
Labels: experiment

#117 PR - Create build.yml
  .github/workflows/build.yml
Labels: experiment

#128 F/release scripts
  .gitattributes
  README.md
  run-macos.sh
Labels: bug

#129 'Fix scripts for running node-darwin and node-linux'
  run-darwin.sh
  run-linux.sh
  run-macos.sh
Labels: bug
