Repository chihab-inc/myPortal, pull requests merged in 2023-08, with the labels that each got.

#37 Update README.md
  README.md
Labels: bug

#39 Can update sections
  public/script.js
  public/sectionDB.js
Labels: Feature

#40 Fixed
  public/script.js
  public/style.css
Labels: bug

#43 Fixed
  public/script.js
Labels: bug

#45 Fixed
  public/script.js
Labels: bug

#46 PR - f/add-new-section
  public/icons/plus-large.png
  public/script.js
  public/style.css
Labels: Feature

#49 PR - fix/link-section-update
  public/script.js
  public/sectionDB.js
Labels: bug

#53 PR - f/release-file-ignore
  .gitattributes
Labels: Feature

#54 PR - f/update-gitignore
  .gitignore
  .vscode/settings.json
Labels: Feature

#55 PR - e/section-add-button-feedback
  public/style.css
Labels: enhancement

#56 PR - f/delete-section
  public/script.js
Labels: Feature

#58 Delete links with section
  public/linkDB.js
  public/script.js
Labels: Feature
